# Generated by Django 3.2.7 on 2021-09-19 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_auto_20210918_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
