# Generated by Django 3.2.7 on 2021-09-24 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0005_auto_20210923_2157'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplieraccountnumber',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='supplieraccountnumber',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_account_numbers', to='suppliers.supplier'),
        ),
    ]
