# Generated by Django 3.2.7 on 2021-09-14 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Staff', 'verbose_name_plural': 'Staff'},
        ),
    ]
