# Generated by Django 3.2.7 on 2021-09-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
